Persentetion/Controllers/ClassRoomController.cs
using Domain.Abstracts;
using Microsoft.AspNetCore.Mvc;
using Models;

namespace Persentetion.Controllers
{
    public class ClassRoomController : Controller
    {
        #region [Ctor]
        private readonly IClassRoomService _classRoomService;
        public ClassRoomController(IClassRoomService classRoomService)
        {
            _classRoomService = classRoomService;
        } 
        #endregion

        #region Index
        [HttpGet]
        public IActionResult Index(int schoolId)
        {
            ViewBag.schoolId = schoolId;
            var list = _classRoomService.GetAll(schoolId);
             return View(list);
        }

        #endregion

        #region Create
        [HttpGet]
        public ViewResult Create(int SchoolId)
        {
            var model = _classRoomService.GetNewModelForCreate(SchoolId);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ClassRoomModel model)
        {
            var result = _classRoomService.Insert(model);
            if (result.IsSuccess)
            {
                return Redirect($"Index?schoolId={model.SchoolId}");
            }
            else
            {
                ViewBag.Message = result.Message;
                model.SchoolSelectList = _classRoomService.GetNewModelForCreate(model.SchoolId).SchoolSelectList;
                return View(model);
            }

        }
        #endregion

        #region Edit
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var model = _classRoomService.GetById(id);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ClassRoomModel model)
        {
            var result = _classRoomService.Update(model);
            if (result.IsSuccess)
                return RedirectToAction("Index");
            ViewBag.Message = result.Message;
            return View(model);
        }
        #endregion

        #region Delete

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var model = _classRoomService.GetById(id);
            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(ClassRoomModel model)
        {
            var result = _classRoomService.Delete(model.Id);
            if (result.IsSuccess)
                return RedirectToAction("Index");
            ViewBag.Message = result.Message;
            return View(model);
        }
        #endregion
    }
}

Persentetion/Views/ClassRoom/Create.cshtml
@model Models.ClassRoomModel
@{
    string Message = ViewBag.Message;
}
@if (!string.IsNullOrWhiteSpace(Message))
{
    <div class="alert alert-danger">
        <span>Insert Has an Error </span>
        <br />
        @Message
    </div>
}
<form action="\ClassRoom\Create" method="post" asp-antiforgery="true" >
    <input type="hidden" asp-for="SchoolId" />
    <div class="row col-md-12">
        <div class="form-group col-md-3">
            <label class="lable">
                Class Name
                <input type="text" class="form-control" asp-for="Name" autocomplete="off" placeholder="Please Enter Name" />
            </label>
        </div>
        <div class="form-group col-md-3">
            <label class="lable">
                Age Range
                <input type="number" class="form-control" asp-for="AgeRange" autocomplete="off" />
            </label>
        </div>
        <div class="form-group col-md-3">
            <button type="submit" class="btn btn-sm alert-primary btn-primary btn1234" style="margin-top:29px"> save</button>
        </div>
    </div>
</form>

Persentetion/Views/ClassRoom/Index.cshtml
 @model List<Models.ClassRoomModel>
@{
    ViewData["title"] = "ClassRoom list";
    var schoolId = (int) ViewBag.schoolId;
}
<div class="row">


    <a asp-action="Create" asp-route-schoolId="@schoolId" class="btn btn-primary btn-md" mb-2">
        <i class="fas fa-plus"></i>
        افزودن کلاس جدید
    </a>

    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>School Name</th>
                <th>AgeRange</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.Name</td>
                    <td>@item.SchoolId</td>
                    <td>@item.AgeRange</td>
                    <td>
                        <a href="/ClassRoom/edit?id=@item.Id" class="btn btn-danger  btn-group ">
                            <i class="fas fa-edit"> </i>
                            ویرایش
                        </a>

                        <a asp-controller="ClassRoom" asp-action="Delete" asp-route-id=@item.Id class="btn btn-warning  btn-group ">
                            <i class="fas fa-trash"> </i>
                            حذف
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    </>
</div>