Persentetion/Controllers/SchoolController.cs
using Domain.Abstracts;
using Microsoft.AspNetCore.Mvc;
using Models;

namespace Persentetion.Controllers
{
        #region Ctor
    public class SchoolController : Controller
    {
        private readonly ISchoolService _schoolService;
        public SchoolController(ISchoolService schoolService)
        {
            _schoolService = schoolService;
        }

        #endregion

        #region Index
        [HttpGet]
        public IActionResult Index()
        {
            var list = _schoolService.GetAll();
            return View(list);
        }

        #endregion

        #region Create
        [HttpGet]
        public ViewResult Create()
        {
            return View(new SchoolModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(SchoolModel model)
        {
            var result = _schoolService.Insert(model);
            if (result.IsSuccess)
            {
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.Message = result.Message;
                return View(model);
            }

        }
        #endregion

        #region Edit
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var model = _schoolService.GetById(id);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(SchoolModel model)
        {
            var result = _schoolService.Update(model);
            if (result.IsSuccess)
                return RedirectToAction("Index");
            ViewBag.Message = result.Message;
            return View(model);
        }
        #endregion

        #region Delete

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var model = _schoolService.GetById(id);
            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(SchoolModel model)
        {
            var result = _schoolService.Delete(model.Id);
            if (result.IsSuccess)
                return RedirectToAction("Index");
            ViewBag.Message = result.Message;
            return View(model);
        } 
        #endregion
    }
}

Persentetion/Views/School/Create.cshtml
@model Models.SchoolModel
@{
    string Message = ViewBag.Message;
}
@if (!string.IsNullOrWhiteSpace(Message))
{
    <div class="alert alert-danger">
        <span>Insert Has an Error </span>
        <br />
        @Message
    </div>
}
<form action="\School\Create" method="post" asp-antiforgery="true" >
    <div class="row col-md-12">
        <div class="form-group col-md-3">
            <label class="lable">
                School Name
                <input type="text" class="form-control" name="Model.Name" value="@Model.Name" autocomplete="off" placeholder="Please Enter Name" />
            </label>
        </div>
        <div class="form-group col-md-3">
            <label class="lable">
                Phone Number
                <input type="tel" class="form-control" name="Model.PhoneNumber" value="@Model.PhoneNumber" autocomplete="off" placeholder="Please Enter +98...."/>
            </label>
        </div>
        <div class="form-group col-md-3">
            <button type="submit" class="btn btn-sm alert-primary btn-primary btn1234" style="margin-top:29px"> save</button>
        </div>
    </div>
</form>

Persentetion/Views/School/Delete.cshtml
@model SchoolModel
@{
    string Message = ViewBag.Message;
}
@if (!string.IsNullOrWhiteSpace(Message))
{
    <div class="alert alert-danger">
        <span>Insert Has an Error </span>
        <br />
        @Message
    </div>
}
<form action="\School\Delete" method="post">
    <input type="hidden" name="model.Id" value="@Model.Id" />
    <div class="row col-md-12">
        <div class="form-group col-md-3">
            <label class="lable">
                School Name
                <input type="text" class="form-control" disabled name="Model.Name" value="@Model.Name" autocomplete="off" placeholder="Please Enter Name" />
            </label>
        </div>
        <div class="form-group col-md-3">
            <label class="lable">
                Phone Number
                <input type="tel" class="form-control" disabled name="Model.PhoneNumber" value="@Model.PhoneNumber" autocomplete="off" placeholder="Please Enter +98...." />
            </label>
        </div>
        <div class="form-group col-md-3">
            <button type="submit" class="btn btn-sm btn-danger" style="margin-top:29px"> Delete</button>
        </div>
    </div>
</form>

Persentetion/Views/School/Edit.cshtml
@model SchoolModel
@{
    string Message = ViewBag.Message;
}
@if (!string.IsNullOrWhiteSpace(Message))
{
    <div class="alert alert-danger">
        <span>Insert Has an Error </span>
        <br />
        @Message
    </div>
}
<form action="\School\Edit" method="post" asp-antiforgery="true" >
    <input type="hidden" name="model.Id" value="@Model.Id" />
    <div class="row col-md-12">
        <div class="form-group col-md-3">
            <label class="lable">
                School Name
                <input type="text" class="form-control" name="Model.Name" value="@Model.Name" autocomplete="off" placeholder="Please Enter Name" />
            </label>
        </div>
        <div class="form-group col-md-3">
            <label class="lable">
                Phone Number
                <input type="tel" class="form-control" name="Model.PhoneNumber" value="@Model.PhoneNumber" autocomplete="off" placeholder="Please Enter +98...." />
            </label>
        </div>
        <div class="form-group col-md-3">
            <button type="submit" class="btn btn-sm btn-warning" style="margin-top:29px"> Edit</button>
        </div>
    </div>
</form>

Persentetion/Views/School/Index.cshtml
@model List<Models.SchoolModel>
@{
    ViewData["title"] = "School list";
}
<div class="row">


    <a asp-action="Create" class="btn btn-primary btn-md" mb-2">
        <i class="fas fa-plus"></i>
        افزودن مدرسه جدید
    </a>

    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>PhoneNumber</th>
                <th>Create Date</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.Name</td>
                    <td>@item.PhoneNumber</td>
                    <td>@item.CreateDate</td>
                    <td>
                        <a href="/School/edit?id=@item.Id" class="btn btn-danger  btn-group ">
                            <i class="fas fa-edit"> </i>
                            ویرایش
                        </a>

                        <a href="/ClassRoom/Index?schoolId=@item.Id" class="btn btn-dark  btn-group ">
                            <svg width="16" height="16" fill="currentColor" class="bi bi-bank2" viewBox="0 0 16 16">
                                <path d="M8.277.084a.5.5 0 0 0-.554 0l-7.5 5A.5.5 0 0 0 .5 6h1.875v7H1
                               .5a.5.5 0 0 0 0 1h13a.5.5 0 1 0 0-1h-.875V6H15.5a.5.5 0 0 0 .277-.916l-7.5-5zM12.375
                              6v7h-1.25V6h1.25zm-2.5 0v7h-1.25V6h1.25zm-2.5 0v7h-1.25V6h1.25zm-2.5 0v7h-1.25V6h1
                            .25zM8 4a1 1 0 1 1 0-2 1 1 0 0 1 0 2zM.5 15a.5.5 0 0 0 0 1h15a.5.5 0 1 0 0-1H.5z" />
                            </svg>
                            <i class="bi bi-bank2"></i>
                            کلاس ها
                        </a>
                        <a asp-controller="School" asp-action="Delete" asp-route-id=@item.Id class="btn btn-warning  btn-group ">
                            <i class="fas fa-trash"> </i>
                            حذف
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    </>
</div>